from decouple import config

POSTGRES_DB = config('POSTGRES_AUTH_DB')
POSTGRES_USER = config('POSTGRES_AUTH_USER')
POSTGRES_PASSWORD = config('POSTGRES_AUTH_PASSWORD')
POSTGRES_HOST = config('POSTGRES_AUTH_HOST')
REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379)
AUTH_PRIVATE_KEY = config('AUTH_PRIVATE_KEY')
TOKEN_LIFETIME_SEC = config('TOKEN_LIFETIME_SEC', 300)

SLA_SERVICE_RESPONSE_MS = config('SLA_SERVICE_RESPONSE_MS', cast=int, default=100)
EXTERNAL_SERVICES_INTERACTION_MEAN_MS = 30
IO_BOUND_COST_MS = 10
SERVICE_BACKOFF_TIMEOUT = (SLA_SERVICE_RESPONSE_MS - EXTERNAL_SERVICES_INTERACTION_MEAN_MS - IO_BOUND_COST_MS) / 1000
