from decouple import config

POSTGRES_DB = config('POSTGRES_AUTH_DB')
POSTGRES_USER = config('POSTGRES_AUTH_USER')
POSTGRES_PASSWORD = config('POSTGRES_AUTH_PASSWORD')
POSTGRES_HOST = config('POSTGRES_AUTH_HOST')
REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379)
AUTH_PRIVATE_KEY = config('AUTH_PRIVATE_KEY')
TOKEN_LIFETIME_SEC = config('TOKEN_LIFETIME_SEC', 300)
