#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database roles"

$POSTGRES <<-EOSQL
CREATE USER ${ETL_DB_USER} WITH SUPERUSER PASSWORD '${ETL_DB_PASSWORD}';
CREATE USER ${POSTGRES_AUTH_USER} WITH SUPERUSER PASSWORD '${POSTGRES_AUTH_PASSWORD}';
EOSQL